### ISSUE TITLE
Error adding cipher to folder

### ISSUE THREAD

**Issue by bassarf** [dani-garcia/bitwarden_rs#344] opened 2019-01-16 18:37 UTC
When adding an item and assigning that to a folder during the creating process I get an "Error adding cipher to folder" error. In the original bitwarden server this is no problem.

### Steps to reproduce
This should work with any app (web, android, browser-plugin,...)
1. hit the "+" or create entry button
1. put in some test entry stuff
1. make sure that a folder is selected
1. try to save it
1. get the error message

Worth noting that: when you create an item and you edit it and move it to a folder _after_ it is created, that is no problem. Just in the initial creation process we get this error

**Comment by dani-garcia** [comment] 2019-01-16 18:46
This is probably caused by https://github.com/dani-garcia/bitwarden_rs/commit/4bf32af60e7687c4e13650d2b232679817cefde7#diff-7ffdd184901080a75ec655b1a20c3c7e, specifically moving the save after the move. When the cipher doesn't exist, we can't create the cipher<->folder mapping.

**Comment by dani-garcia** [comment] 2019-01-16 19:00
Should be fixed now, in https://github.com/dani-garcia/bitwarden_rs/commit/1ce2587330090d79c7d29d66ea6786b866e9e6d0.

**Closed by dani-garcia** 2019-01-16 19:00 UTC

**Comment by bassarf** [comment] 2019-01-18 12:35
just reporting back, that I could test it successfully.
Thank you for the quick fix
