### ISSUE TITLE
Problem creating more than 79 Organizations

### ISSUE THREAD

**Issue by fablav** [dani-garcia/bitwarden_rs#1232] opened 2020-11-20 14:25 UTC
### Subject of the issue
User crash after creating the 79th Organization

### Your environment
Bitwarden_rs server in Docker on a Nas Synology
* Bitwarden_rs version:
2.16.1
* Install method: Download image by repository in Docker
* Clients used: Synology Nas with DSM DSM 6.2.3-25426
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information:

### Steps to reproduce
After creating an account, i try to create the Organizations.
Everything is okay until creating the 79th Organization.
After creating that, the Account loose all the Organizations created.
In the Admin Panel I can see them but in the Portal there is nothing.
My account is locked and I can't create new Organization.

**Comment by BlackDex** [comment] 2020-11-20 15:14
Hello @fablav, to be blunt, why do you need 79+ Organizations?
That seems to be a lot, and not very manageable.

Also, what are the error's you get either in the bitwarden.log or the browser developer console?

**Comment by fablav** [comment] 2020-11-20 15:49
Hello @BlackDex 
We are a company that has to manage the paswords of our customers (over 150).
we would like to enter their organisation and invite them for a read only access.
I dond't have the log because I've deleted the Docker Container.
I can reproduce the error reinserting the Organizations, but I don't know where find the log.
I have poor knowledge about Docker and Bitwarden.

**Comment by BlackDex** [comment] 2020-11-20 16:46
Well that is unfortunate. Without that i can't help to troubleshoot this issue.
I just tried creating 100 organizations, and that works fine for me.
If you try it again, please save the log output and browser errors you may see in the developer console (F12) of the browser.

![Screenshot-Bitwarden_RS-Web-Vault-100plus-orgs](https://user-images.githubusercontent.com/610450/99826160-4504f000-2b58-11eb-9f6a-0451a942284e.png)

**Comment by BlackDex** [comment] 2020-11-22 16:03
Closing this ticket because it's not reproducible and it seems the original logs are going as stated by the reporter.
If someone has this issue also, and has logs, please re-open.

**Closed by BlackDex** 2020-11-22 16:03 UTC
Labels: troubleshooting
