### ISSUE TITLE
User with readonly access to collection entry can edit entry

### ISSUE THREAD

**Issue by 0xERR0R** [dani-garcia/bitwarden_rs#276] opened 2018-12-07 14:41 UTC
Environment: last docker version

Given: User A creates an item and shares it to the default collection of organization. User B has only readonly access to this Collection

When: User B opens the shared item, he can edit it (in web vault), which is wrong. The item should apper as read only item. User B can click on save and gets error "an unexpected error is occured". Server log: "ERROR: Cipher is not write accessible".

So this is only a UIproblem, the item can't be changed

**Comment by dani-garcia** [comment] 2018-12-09 18:58
So, I made a quick test in the official web vault and the ui acts the same way. The server sends a field `edit` which is true when the cipher is editable, but the ui doesn't seem to reflect it.

For now, I fixed the errors in the latest beta so they show less generic messages in the clients.

**Comment by mprasil** [comment] 2018-12-10 15:30
I think we can close this as one part of the problem is upstream and the other was fixed in beta.

**Closed by mprasil** 2018-12-10 15:30 UTC
Labels: bug
