### ISSUE TITLE
invalid user/pass, but actual reason: disk full

### ISSUE THREAD

**Issue by tfriedel** [dani-garcia/bitwarden_rs#1062] opened 2020-07-21 08:10 UTC
### Subject of the issue
One day I tried to login to bitwarden rs and it said email/pass combination is wrong, even though it wasn't.

### Your environment
* Bitwarden_rs version: 2.13.2 

* Install method: docker image (part of hass / home assistant)
* Clients used: web, android
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information: 
I tried restarting bitwarden_rs and it didn't even start. Then I noticed that the disk was full. After making some space, it worked again.
### Steps to reproduce
You could set up a virtual disk, install bitwarden rs and fill it. Didn't try this though.
### Expected behaviour
Ideally it should continue working, since just accessing my passwords should not require write operations. I understand there's logs being written etc and it's maybe too much trouble to implement. But it's a very critical piece of software, so it would be nice if it would continue to work even under less ideal circumstances.
Failing that, a different error message then user/pass incorrect might be appropriate ("Disk full" for example). It might also ideally warn me somehow, if disk space is running low.

**Comment by dani-garcia** [comment] 2020-07-21 14:37
There are actually some write operations during login, to save the refresh token for the devices for example, which I assume are the cause of the problem.

That said handling this use case is out of scope of the project, and should be managed instead with some monitoring software, or a separate partition dedicated to bitwarden_rs.

**Closed by dani-garcia** 2020-07-21 14:37 UTC

**Comment by colinfrei** [comment] 2020-07-24 10:59
fwiw I had the same issue, and only figured out what the problem was due to this issue. 
Maybe it'd just be possible to catch the error and output a different error message?
