### ISSUE TITLE
Problems on a Raspberry Pi 3 Model B+

### ISSUE THREAD

**Issue by xMateMCPE** [dani-garcia/bitwarden_rs#174] opened 2018-09-11 19:01 UTC
After installing the program as its specified in the readme to 2 Raspberry Pi 3 Model B+ devices, the only thing that shows up after going to the site is the _Apache2 Debian Default Page_ , both devices have stock Raspbian, the only thing that was installed by me on them is Docker
![Picture](https://user-images.githubusercontent.com/29177144/45381489-b7d3c180-b605-11e8-8cc9-1842303c803a.png)

**Comment by mprasil** [comment] 2018-09-11 19:17
Hi, did you compile it yourself? As for the default Apache page, this looks like Apache misconfiguration. There's nothing in Bitwarden that would generate such page.

**Comment by xMateMCPE** [comment] 2018-09-11 20:03
I used the docker image with the commands that were the first thing in the readme

**Comment by dobunzli** [comment] 2018-09-11 20:31
Hello,

Just in case, I have it installed on a raspberry pi 3b+ running Arch Linux, but without docker. 

I used these packages https://aur.archlinux.org/packages/bitwarden_rs/ and https://aur.archlinux.org/packages/bitwarden_rs-vault/ and was able to make it work locally for now.

I am still configuring the serveur so I can access from the outside world... and progress are made !

Hope this helps.

**Comment by mprasil** [comment] 2018-09-11 21:07
@dobunzli, thanks for update. Makes sense that would work as it's basically building the binary on raspberry. Still cool to hear that people are really running this on such relatively low power HW.

**Comment by xMateMCPE** [comment] 2018-09-12 09:17
Any versions for Raspbian? That is what i need for most projects so i cannot switch to Arch Linux

**Comment by mqus** [comment] 2018-09-12 09:32
And if you need, I also threw a .service file for systemd together [here](https://aur.archlinux.org/cgit/aur.git/tree/bitwarden_rs.service?h=bitwarden_rs) but you may have to change the paths to match your binary, .env file and working directory (the directory where `web-vault/` is in). The modified `bitwarden_rs.service` file then goes into `/etc/systemd/system` and can be enabled/started like all the other systemd services.

**Comment by mprasil** [comment] 2018-09-12 09:43
Yeah for now you have to build it yourself. You can actually download the docker image you were trying to use and copy the web-vault folder out of there instead of building the Vault part yourself.

**Comment by mprasil** [comment] 2018-09-12 14:33
Guys, if you have raspberry, can you give it a try with `mprasil/bitwarden:beta-raspberry` image? I have no hardware to test it on and it's using cross-compiling for everything, so a test on real raspberry would be appreciated.

**Comment by dobunzli** [comment] 2018-09-12 19:57
Hello,

I can confirm that this image launches correctly on a raspberry 3 b+ with raspbian desktop june 2018 after installing docker and docker-compose.
I only tested from the local network for now, but everything looks good !

Thanks for the work !

**Comment by mprasil** [comment] 2018-09-12 21:07
Thanks for testing! @xMateMCPE give it a go, it should hopefully work on your raspbian. It's current master version just compiled for ARMv7, so it should be just the same as `mprasil/bitwarden:latest` functionally.

**Comment by xMateMCPE** [comment] 2018-09-12 21:30
Just a question, how do i install it? I tried the docker install didn't work, i tried compiling it but i cannot get the OpenSSL 1.0.2 version anywhere

**Comment by mprasil** [comment] 2018-09-12 21:38
Just use the normal docker run commands as you see in the readme, but instead of `mprasil/bitwarden:latest` image, use `mprasil/bitwarden:beta-raspberry`. That should be the only difference.

**Comment by dobunzli** [comment] 2018-09-12 21:54
Hello,

Hope this helps:

Docker installation

curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh

sudo usermod -aG docker pi

Docker-compose installation (not sure if it is the latest but that's what I did)

sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` - /usr/local/bin/docker-compose

chmod +x /usr/local/bin/docker-compose

Bitwarden raspberry installation

docker pull mprasil/bitwarden:beta-raspberry

Launch

sudo docker run -d --name bitwarden -v /bw-data/:/data/ -p 80:80 mprasil/bitwarden:beta-raspberry

Try
 Launch a browser and use http://localhost:80

**Comment by xMateMCPE** [comment] 2018-09-13 12:52
It works! Thanks. :)

**Comment by mprasil** [comment] 2018-09-13 14:21
Perfect! I'll resolve this, we now have the raspberry Dockerfile merged, so hopefully the non-beta raspberry image should appear soon. (just in the build pipe, but will take couple hours to build)

**Closed by mprasil** 2018-09-13 14:21 UTC
Labels: question, troubleshooting

**Comment by mprasil** [comment] 2018-09-13 19:40
Update: the image is ready, please use `mprasil/bitwarden:raspberry` image on raspberry pi.
