### ISSUE TITLE
Attachments can be downloaded without authorisation

### ISSUE THREAD

**Issue by ntimo** [dani-garcia/bitwarden_rs#729] opened 2019-11-16 23:19 UTC
Hello,
Currently the API does not check if the user is authorized to download the encrypted attachment file via /attachments/. 

It would be quite nice to have somekind of authentication here. So that it is not possible to download attachments without having a active session. I also noted that vault.bitwarden.com does the same :( . 

Best wishes,
Timo

**Comment by mprasil** [comment] 2019-11-17 00:37
Yeah, unfortunately this is limitation on the Bitwarden side and I'm not sure what we can do about it. I assume the reason why it's implemented that way in the upstream is that they can offload attachment handling to "dumb" http server. (or even something like S3) On the plus side attachments are decrypted client side. So even if someone managed to guess the attachment URL (which is pretty hard with that uuid) they still wouldn't get the contents.

**Comment by ntimo** [comment] 2019-11-17 08:45
Maybe we could limit by IP address? I think that should work. So if we know that the user has a active session with IP xy then this IP is allowed to download attachments for this user.

**Comment by mprasil** [comment] 2019-11-17 14:50
Not really. The active session is very loose concept. You can have mobile client logging in and then fetch the attachment hours later from completely different network.

**Comment by mprasil** [comment] 2019-11-27 12:04
I'm going to close this as it's essentially working as intended. (trying to be upstream compatible)

**Closed by mprasil** 2019-11-27 12:04 UTC
