### ISSUE TITLE
Disable Organizations

### ISSUE THREAD

**Issue by Warlord1390** [dani-garcia/bitwarden_rs#752] opened 2019-11-29 21:37 UTC
Can you advise if there is a way to disable organizations to remain compliant with a free license structure?

**Comment by mprasil** [comment] 2019-11-29 23:22
You can just not create organization. But if you want to prevent any user from creating organization, it should be easy to add an toggle for that, it's just nobody wanted this so far. It would not be 100% the same though as free online account gives you ability to create "family" style organization and share passwords with one user. This would be considerably more effort to implement though.

**Comment by dani-garcia** [comment] 2019-11-30 22:38
We could try making the user JSON return `Premium: false`, maybe that enables all the limits client side. Of course someone could modify the clients to ignore that, but as this isn't a security feature and more of a compliance thing maybe that's enough.

**Comment by Warlord1390** [comment] 2019-12-02 15:12
From my perspective, having the the front end limited by a backend toggle "Premium: false" would more than suffice.

**Comment by dani-garcia** [comment] 2019-12-02 18:55
Okay so I just tested it and that's not enough, that simply shows the please buy premium banner.

To support this then, we'd have to limit users to 1 organization in the server code. Do you also want to follow the rest of the free tier restrictions (no attachments, no 2FA other than TOTP and no two factor secret storage)?

**Comment by Warlord1390** [comment] 2019-12-02 20:34
I would like that option available to restrict the server to only free tier subscription if it is not too much to ask. 

Thank you!

**Comment by pdarcos** [comment] 2019-12-29 19:39
Did this get introduced into the code lately?

The reason I ask is that I can no longer create organizations in my account (I recently recompiled everything from latest master branch)

![bitwarden_rs](https://user-images.githubusercontent.com/32959420/71561781-fa2b4700-2a72-11ea-9039-109fcd9ca8a0.png)

**Comment by gramakri** [comment] 2020-01-08 06:39
From what I understand from https://help.bitwarden.com/article/what-is-an-organization/, orgs are not a premium feature. I don't see the upload license file message that @pdarcos is seeing in my build atleast.

**Comment by marier-nico** [comment] 2020-02-14 20:33
Jumping in because I feel like my question is related, but would it be possible to limit organization creation to certain users (or the admin interface)? My use-case is that I want to invite family and friends to separate organizations for convenience, but I don't really want them creating organizations and inviting external users. Sure, I could tell them not to, but it would be a cool feature to have I think!

**Comment by mprasil** [comment] 2020-02-16 12:09
@marier-nico I think you can sort of do what you want [by setting `INVITATIONS_ALLOWED=false`](https://github.com/dani-garcia/bitwarden_rs/blob/8867626de898bb8416ed8319806b1c220d57dcb1/.env.template#L126). This will still let other users create organizations and invite each other, but it won't allow them to invite new users onto your server.

**Comment by marier-nico** [comment] 2020-02-16 14:45
@mprasil Yeah, I tried that setting and the issue is that if I use it, then I can't invite anyone either even through the admin panel, so if I used it I'd need to restart the server every time I wanted to add someone, which I could do, but I was just hoping there would be a more convenient way to do it.

**Comment by mprasil** [comment] 2020-02-16 14:56
Yeah it's because of [code here](https://github.com/dani-garcia/bitwarden_rs/blob/master/src/api/admin.rs#L156). But it makes me wonder if that piece of code makes any sense there. The only way to call that endpoint is with admin token and anyone with admin token can also change the setting..

I'll submit a PR removing that condition there to unlock your use case, I think the API endpoint would make more sense that way.

**Comment by marier-nico** [comment] 2020-02-16 15:25
That does make more sense, yeah. Thanks a lot for looking into this! :smile:

**Comment by mprasil** [comment] 2020-02-16 21:55
@marier-nico  that PR was now merged. Give it ~24h to build all the images and you can limit the invitations to admin interface.

**Closed** 2020-10-03 23:38 UTC
