### ISSUE TITLE
Failed to fetch error with MS Edge Extension

### ISSUE THREAD

**Issue by diehardbattery** [dani-garcia/bitwarden_rs#192] opened 2018-09-19 02:47 UTC
I am running the latest Windows 10 Pro v1803 build 17134.285, and Latest MS Edge v42.17134.1.0.  This is installed on a Qnap NAS.  I am pretty new to Qnap/Docker so I'm not sure how to provide any more information.  Other than this issue, it is working on all my other devices meaning apps/extensions work fine.

**Comment by dani-garcia** [comment] 2018-09-19 11:26
I think the Windows 10 apps have communication blocked with localhost by default. There is a setting to change it for edge in the developer settings but as edge extensions are counted as separate apps, maybe that needs to be changed for the bitwarden extension too?

https://stackoverflow.com/questions/30334289/cant-open-localhost-in-microsoft-edge-project-spartan-in-windows-10-preview

**Comment by diehardbattery** [comment] 2018-09-19 12:38
That option is already enabled.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by shauder** [comment] 2018-09-19 14:07
I found how to debug an extension in edge. Seems like we are on the right track with what the issue is.  I think your best bet will be running it behind a reverse proxy. You'll also get websockets this way if you configure it right.  

I messed around with some settings and I am able to get edge to show the local vault but I am unable to get the extension to communicate still.

```HTML1300: Navigation occurred.
background.html (1,1)

 HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "!DOCTYPE html>".
background.html (1,1)

 API Call 'browserAction.setIcon' has been bridged to another Edge API: browserAction.setIcon with absolute path

 CONSOLE21301: serviceWorker.getRegistrations is rejected due to unsecure context or host restriction in ms-browser-extension://EdgeExtension_8bitSolutionsLLCbitwardenFreePasswordManager_h4e712dmw3xyy/background.html.

**Comment by shauder** [comment] 2018-09-19 21:09
@diehardbattery try running this (restart edge after and run in administrator powershell):

https://stackoverflow.com/questions/32384571/why-does-microsoft-edge-open-some-local-websites-but-not-others-where-the-doma

Run:
`CheckNetIsolation LoopbackExempt -a -n="Microsoft.MicrosoftEdge_8wekyb3d8bbwe"`

This fixed it for me in my test environment

**Comment by dani-garcia** [comment] 2018-12-13 18:04
This hasn't had activity in some time, so I'm closing it now.
If this is still an issue, please reopen it.

**Closed by dani-garcia** 2018-12-13 18:04 UTC
Labels: help wanted, troubleshooting
