### ISSUE TITLE
Bitwarden_rs Docker on LCOW: Database errors

### ISSUE THREAD

**Issue by djpbessems** [dani-garcia/bitwarden_rs#399] opened 2019-02-15 21:53 UTC
I'm trying to run the bitwarden_rs dockerimage on Windows Server 2019 with Linux Containers On Windows (LCOW).

I'm using the command  
`docker run -d --name bitwarden -v C:/path/to/bitwarden/conf:/data -p 80:80 -e "RUST_BACKTRACE=1" mprasil/bitwarden:latest`  
which results in the error  
`thread 'main' panicked at 'Failed to turn on WAL: DatabaseError(__Unknown, "disk I/O error")'` (it creates several files in C:\path\to\bitwarden\conf)  
and subsequent runs change the error to  
`thread 'main' panicked at 'Can't run migrations: QueryError(DatabaseError(__Unknown, "disk I/O error"))'`

Permissions for the path C:\path\to\bitwarden\conf are set to FullControl for Users (temporarily for testing purposes); but the errors remain.

What possible troubleshooting steps could I still follow?

**Comment by BlackDex** [comment] 2019-02-16 14:12
What i can find quickly on the internet is that this is an LCOW issue.
I read stuff about disable the shared drive, reboot, re-enable the shared drive again. Or try the reset credentials link at that same menu. It seems to have something to do with the credentials not being set right for the LCOW usage.

This issue has nothing to do with bitwarden_rs it self, since it only uses normal filesystem operations and is restricted by what the docker environment allows.

Hope the credentials part in the LCOW settings will help you.
Please let us know if that solves your issue.

**Comment by mprasil** [comment] 2019-02-16 22:22
Yeah, we're [enabling `WAL` here](https://github.com/dani-garcia/bitwarden_rs/blob/6027b969f542b29365875fa78dbf77765b12d290/src/main.rs#L172-L174) for performance reasons and it sounds like your filesystem (or whatever windows emulates) doesn't support that in current configuration. Try to follow @BlackDex's advice to see if you can enable it.

Alternatively we might look into optionally not enabling [`WAL`](https://sqlite.org/wal.html). I think it would be a useful feature for cases like this, but in the past we had some `SQLITE_BUSY` related issues where some operations (especially "heavy ones") sometimes (rarely, but still) failed. We've since added some code handling these problems, but disabling `WAL` would have to go with the understanding, that it's somewhat non-standard configuration that might sometimes cause issues.

**Comment by dani-garcia** [comment] 2019-02-16 22:28
Yeah, WAL on LCOW seems to be a problem (https://github.com/docker/for-win/issues/1385#issuecomment-385177466, https://github.com/Sonarr/Sonarr/issues/1886).

As a possible alternative, you could install Rust and [compile the project yourself](https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary). It should work fine in that case.

**Comment by djpbessems** [comment] 2019-02-17 10:19
@BlackDex I'm using Docker for Windows Enterprise Edition; it does not have the weird requirement of sharing your entire volumes.

Probably I'll have to bite the bullet and dive in this matter: I'll try and create a new dockerimage based on Windows Nanoserver so LCOW is not involved. Mind if I ask for pointers now and then? Once I get it working you can offer it as a semi-official alternative :)

**Comment by dani-garcia** [comment] 2019-02-17 10:56
Sure thing, we can help you here, or on the matrix chat room. The link is on the Readme.

**Comment by mprasil** [comment] 2019-02-18 10:52
I've created a PR #404 that will allow you to not use WAL by setting the ` ENABLE_DB_WAL` variable to `false`.

**Comment by djpbessems** [comment] 2019-02-18 13:35
Oh, awesome; are you going to merge and build that into mprasil/bitwarden dockerimage? Or should I build it myself and try?

**Comment by mprasil** [comment] 2019-02-18 15:02
The idea is that this will be added to the official image soon if @dani-garcia is okay with the changes. So you can wait, but can also build your own image in the meantime if you're super eager to try it now. 😄

**Comment by mprasil** [comment] 2019-02-18 15:53
Changes are now merged, you can see the documentation [here](https://github.com/dani-garcia/bitwarden_rs/wiki/Running-without-WAL-enabled)

Note that the build was just scheduled and will take about an hour. If you want to test it now, you can use our dev image that was built just now: `bitwardenrs/dev:master`, otherwise wait about two hours and use `mprasil/bitwarden` as usual.

Let us know if it runs fine with WAL disabled.

**Comment by djpbessems** [comment] 2019-02-19 07:56
Thanks for this; it seems to run quite stable regardless :)

**Comment by mprasil** [comment] 2019-02-19 10:50
Yeah I wouldn't be that much worried about stability. We had some rare cases where some calls would fail (just report `500`, not crash or anything like that) due to some concurrency issues on sqlite. (sharing passwords with attachments was one of these) But normal usage wasn't affected by this at all. We've also added couple retries where we would previously fail at first try and recently I couldn't reproduce the issue even with really heavy requests. So I think you should be good.

Going to close this as I think it's resolved. If you have some time, maybe do a wiki on the WSL installation, I'm sure some people would be interested. Feel free to reopen or open new issue if you spot some other problems.

**Closed by mprasil** 2019-02-19 10:50 UTC
