### ISSUE TITLE
Architecture property incorrect for non-x86 Docker images

### ISSUE THREAD

**Issue by cerebrate** [dani-garcia/bitwarden_rs#789] opened 2019-12-30 20:33 UTC
The bitwardenrs/server:raspberry image available on the Docker Hub has its os/arch set to linux/amd64 rather than linux/arm - in fact, all the non-x86 images seem to? See [here](https://hub.docker.com/r/bitwardenrs/server/tags) - and so I'm unable to run the image on my Raspberry Pi-based Docker swarm. The service stays in "pending" state, with the error that no compatible nodes are available.

**Comment by mprasil** [comment] 2020-01-03 20:37
I'm closing this as duplicate of #797 as that one already has explanation of what's going on here and it seems to be the same issue. Let's continue the discussion there.

**Closed by mprasil** 2020-01-03 20:37 UTC
