### ISSUE TITLE
HTTP 403 when accessing organization

### ISSUE THREAD

**Issue by Orybon** [dani-garcia/bitwarden_rs#339] opened 2019-01-14 10:46 UTC
Hello, 

Each time i click on an organization i get a 403 Error : 

> Request URL: https://<snip>/api/organizations/<snip>/collections
> Request Method: GET
> Status Code: 403 Forbidden

I'am using the latest version : 

>  docker images | grep bitwarden
> mprasil/bitwarden                                        latest              a8c3e85c60fb        2 days ago          90.5MB

I created the organization.

Here are the errors found in my docker log : 

> bitwarden      | [2019-01-14 10:37:41][rocket::rocket][INFO] GET /api/organizations:
> bitwarden      | [2019-01-14 10:37:41][_][INFO] Matched: GET /<p..> (web_files)
> bitwarden      | [2019-01-14 10:37:41][_][ERROR] Response was a non-`Responder` `Err`: Os { code: 2, kind: NotFound, message: "No such file or directory" }.
> bitwarden      | [2019-01-14 10:37:41][_][INFO] Outcome: Failure
> bitwarden      | [2019-01-14 10:37:41][_][WARN] Responding with 500 Internal Server Error catcher.
> bitwarden      | [2019-01-14 10:37:41][_][INFO] Response succeeded.

**Comment by dani-garcia** [comment] 2019-01-14 17:03
I'm not sure where you get the call to `GET /api/organizations`, I've never seen that one before. The error you are getting is because that endpoint is not implemented. Can you provide the steps used to reproduce the error?

**Comment by Orybon** [comment] 2019-01-14 19:04
I get the call from the DIV on the right side of the home page. When i follow on of the link to an organization.

I tried this evening with my home computer, i can't reproduce the issue. 

So i tracked what is happening on the client side of my work computer (the one i got the error) and it appears that i get a 403 ERROR from the proxy of my work SI.

The error logged previously on server side seems to been unrelated to this issue.

This issue can be closed i think, but i wil investigate later on the root cause of the error logged by the server. 

Thank you.

**Comment by mprasil** [comment] 2019-01-15 10:40
As per your comment, I'm closing this, but feel free to reopen if you manage to reproduce this in some reliable way.

**Closed by mprasil** 2019-01-15 10:40 UTC
