### ISSUE TITLE
Can't enable 2FA

### ISSUE THREAD

**Issue by SlothCroissant** [dani-garcia/bitwarden_rs#260] opened 2018-11-19 00:54 UTC
I couldn't enable 2FA on my new iPhone today when connecting to my vault hosted in Docker, and found that I couldn't login to the web UI with 2FA either. I was able to get in via a 'remembered' browser, and disabled 2FA.

Once I try to enable it, however, I get an "unexpected error" when validating the code (after adding it to Authy). Logs show the following:

```
POST /api/two-factor/get-authenticator application/json; charset=utf-8:
    => Matched: POST /api/two-factor/get-authenticator
    => Outcome: Success
    => Response succeeded.
PUT /api/two-factor/authenticator application/json; charset=utf-8:
    => Matched: PUT /api/two-factor/authenticator
ERROR: Invalid totp code
    => Outcome: Success
    => Response succeeded.
```

i've re-tried this many times with Google Auth, Authy, and Microsoft Authenticator, all with no success. Thoughts?

**Comment by dani-garcia** [comment] 2018-11-19 19:07
I just tried to enable 2fa in a new accout and i can login just fine (this is using the web vault, with the rocket-0.4 branch, I can't compile the master branch at the moment).

Problems with 2fa ususally are caused by different timezones or problems with the clock sync. Can you make sure that both the server and the device connecting have the same time?

**Comment by dani-garcia** [comment] 2018-12-13 18:05
This hasn't had activity in some time, so I'm closing it now.
If this is still an issue, please reopen it.

**Closed by dani-garcia** 2018-12-13 18:05 UTC
Labels: troubleshooting
