### ISSUE TITLE
Somehow make it clear to people that they shouldn't contact official Bitwarden support

### ISSUE THREAD

**Issue by kspearrin** [dani-garcia/bitwarden_rs#336] opened 2019-01-11 04:02 UTC
We frequently get people using these third party servers that contact official support channels for help with problems they are having with it. Lots of times we go back and forth trying to figure out what the problem they are having is only to find out later they are using a third-party server (which they originally fail to mention) and we can't help. This is a drain on resources for the official Bitwarden product. I am not sure what the solution is, but could you brainstorm ideas on how to better communicate to users that they shouldn't do this? I suppose a simple start would be to put a notice in the README or something but I am not sure that is going to solve the problem completely.

Thanks.

**Comment by mprasil** [comment] 2019-01-11 09:17
There's already notice in the readme. I don't think many users actually read that carefully as we'd hope though. To me it looks like many of the users simply reach out to you through the support links in the app. Perhaps we could agree on some API call that would identify third party server (and maybe even the project url or something like that) and direct people there instead? (Or show a warning near the support link explaining that they aren't using official server and where to seek help)

I'm personally fine with people raising issues here first even if it turns out to be client side issue. Just my 2c, @dani-garcia, any thoughts from your side?

**Comment by dani-garcia** [comment] 2019-01-11 12:46
I have some possible ideas:
- I'm sure we could explicitly state in the README that the users should send all the bitwarden-related bug reports here, including dekstop, mobile, and browser bugs, until we are sure the problem is reproducible in the official server. We could also print a message at the start of the server, but I'm not sure how many people would read those, or remember when they have problems.

- As a possible bandage, we could add an element to all the JSON responses with something like 
`"server": "bw_rs"`, and add something like `[BW_RS]` to all the user facing error messages. At least, in that case the origin of the error would be easy to spot.

- I like mprasil's idea of an API endpoint for this, the clients could call `bw-server.com/api/server-info` after changing the server URL and we could return something like this:
  ```json
  {
    "name": "Bitwarden RS",
    "official": false,
    "report_url": "<This_repo>",
  }
  ```

  This way the clients could also validate that the user entered a valid server URL in the field and the apps could change the support links. If people are reaching the official support channels through the app links, then that would solve the problem. 

- As a less effort version of the last point, we could return `"official": false` with the prelogin or login steps and the clients could show a popup indicating that the server is not official and to please not report bugs there.

Of course these last options would be the most complex to implement, so maybe for now we could just focus on the first two?

**Comment by kspearrin** [comment] 2019-01-11 14:32
Thanks guys. Let's just go with the changes to the README and launch message for now and we'll see if things get better.

**Comment by mprasil** [comment] 2019-01-13 00:07
I think we can close this one for now @dani-garcia? The release 1.6.1 with the warning is now out.

**Comment by dani-garcia** [comment] 2019-01-13 00:41
Yeah, let's close it for now to avoid cluttering the list.

If it continues being a problem, we'll reopen it again.

**Closed by dani-garcia** 2019-01-13 00:41 UTC
