### ISSUE TITLE
Feature Suggestion: Use Explicit TLS setting in Web Admin console is misleading

### ISSUE THREAD

**Issue by kevdogg** [dani-garcia/bitwarden_rs#851] opened 2020-02-05 20:49 UTC
Just a comment

Within the bitward_rs Web admin console under the section Labeled: SMTP Email Settings there is an option

Use Explicit TLS with a check box and beside checkbox (Default: true)

So from trial and error -- Explicit TLS IS enabled if box IS NOT checked 
                                            Explicit TLS IS NOT enabled if box IS checked

You can see the confusion in the statements above -- IS enabled <--> IS NOT CHECKED
                                                                                               IS NOT enabled <--> IS CHECKED

Clearly this really creates confusion.  If Explicit TLS is the Default -- then the box should be checked and if NOT Enabled the box should NOT be checked.  

I'm aware this probably didn't make any sense, however honestly some possible recommendations should be added to the GUI like:
(Port 465, Use Implicit TLS), (Port 587, Use Explicit TLS) and something like (Box checked = Implicit DNS, Box NOT checked = Explicit TLS).

**Comment by brentybh** [comment] 2020-04-28 00:11
Exactly... The "Explicit TLS" should be "Implicit TLS", which means TLS by default without upgrade.
Hope we can change this!

**Comment by dani-garcia** [comment] 2020-05-13 22:57
Hmm, you are right it seems i got the names backwards, i can easily change the label in the admin page, but the environment variable (smtp_explicit_tls), I can't change without breaking users configs, and I think changing one but not the other will only make it worse.

**Comment by kevdogg** [comment] 2020-05-13 23:03
Just my two cents...I'm aware about the meanings of implicit vs explicit
but I also understand the confusion these terms cause. Honestly I'm think
it might be better today tie whatever wording you want to use with a
standard port number. Yes I'm aware port numbers can change, but what you
really want to know is ..don't I use port 587 here or 465. I set up my own
postfix relay server at home using both protocols and there are only a
couple different settings that differentiate the two.

I agree change would like break user configs and this might not be the
smartest way to tackle the problem.

**Comment by BlackDex** [comment] 2020-10-09 21:15
I did change the comments and made it more clear in the admin page regarding this.

We could of course add a new one and have that one visible in the admin interface and replace it in the .env.template. but still have the old one there working as it should be when filled?

**Comment by BlackDex** [comment] 2020-11-18 12:33
The comments and descriptions have been fixed in #1148 so closing this issue.
Feel free to re-open if the issue isn't resolved using the `testing`/`master` version.

**Closed by BlackDex** 2020-11-18 12:33 UTC
