### ISSUE TITLE
Error: Cannot read property 'importKey'

### ISSUE THREAD

**Issue by oscartbeaumont** [dani-garcia/bitwarden_rs#153] opened 2018-08-26 10:31 UTC
Hello,
I just came across this project and installed it using the command in the README. When I try to login I get the error below. The error below is copied from the Chromes devtools console. Have I done something wrong or is this a bug?

```
core.js:1440 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'importKey' of null
TypeError: Cannot read property 'importKey' of null
    at n.<anonymous> (webCryptoFunction.service.ts:45)
    at zohoVaultCsvImporter.ts:7
    at Object.next (zohoVaultCsvImporter.ts:7)
    at zohoVaultCsvImporter.ts:7
    at new t (zone.js:887)
    at t (zohoVaultCsvImporter.ts:7)
    at n.pbkdf2 (webCryptoFunction.service.ts:25)
    at n.<anonymous> (crypto.service.ts:276)
    at container.service.ts:4
    at Object.next (container.service.ts:4)
    at n.<anonymous> (webCryptoFunction.service.ts:45)
    at zohoVaultCsvImporter.ts:7
    at Object.next (zohoVaultCsvImporter.ts:7)
    at zohoVaultCsvImporter.ts:7
    at new t (zone.js:887)
    at t (zohoVaultCsvImporter.ts:7)
    at n.pbkdf2 (webCryptoFunction.service.ts:25)
    at n.<anonymous> (crypto.service.ts:276)
    at container.service.ts:4
    at Object.next (container.service.ts:4)
    at O (zone.js:821)
    at zone.js:736
    at r (register.component.html:53)
    at t.invoke (zone.js:388)
    at Object.onInvoke (core.js:4733)
    at t.invoke (zone.js:387)
    at e.run (zone.js:138)
    at zone.js:870
    at t.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4724)```

**Comment by mprasil** [comment] 2018-08-26 10:35
Hi, the console error probably isn't going to be as useful as network view. Try to see if there are any failing requests in the network tab of dev tools. Also do check the logs on the server side. You can post those here. (obviously replacing any sensitive data)

**Comment by oscartbeaumont** [comment] 2018-08-26 11:31
It is not making any web request, It must be failing before that occurs. The command I used to start the server is 
```
docker run -d --name bitwarden -v /bw-data/:/data/ -p 8080:80 mprasil/bitwarden:latest
```
It is weird because I just checked and safari (on the same system) works fine but Chrome fails with the registration (it freezes on the submit button) and the login screen. I am on a Mac if that helps. I also disabled all of my extensions and that hasn't helped.

**Comment by mprasil** [comment] 2018-08-26 11:44
Try to go to the login screen, open the network tab and press ctrl-shift+r to do a full reload. See if any of the requests fail. Perhaps some static file didn't load properly or something like that. It looks like browser/client issue to me, but don't know enough javascript to be sure here.

**Comment by oscartbeaumont** [comment] 2018-08-26 11:52
Everything loads successfully. The last 2 request in the attached image are run when I click submit for the first time after the reload. The second time I click it nothing happens. Both times cause the error popup and it has stopped logging the error to the browser console.
![screen shot 2018-08-26 at 7 48 30 pm](https://user-images.githubusercontent.com/21004798/44627917-332c4680-a969-11e8-9576-b44a7fc96837.png)

**Comment by mprasil** [comment] 2018-08-26 11:56
I suppose it still doesn't log you in though?

**Comment by oscartbeaumont** [comment] 2018-08-26 12:02
I have a self-hosted instance of the official Bitwarden running and the login works perfectly.

**Comment by mprasil** [comment] 2018-08-26 12:09
What version of chrome are you using. I've tried to reduce this with Chromium version 68.0.3440.106 on Ubuntu and it just works for me :confused:

**Comment by oscartbeaumont** [comment] 2018-08-26 12:25
I Am Running Google Chrome 68.0.3440.106 (Official Build) (64-bit) Revision 1c32c539ce0065a41cb79da7bfcd2c71af1afe62-refs/branch-heads/3440@{#794}
On MacOS 10.12.6.

**Comment by oscartbeaumont** [comment] 2018-08-26 12:28
It is also happening on a windows system with the same chrome version.

**Comment by mprasil** [comment] 2018-08-26 12:54
Is there any proxy in between or anything like that?

**Comment by oscartbeaumont** [comment] 2018-08-26 12:55
No not currently but I will add one when I deploy this in the future.

**Comment by mprasil** [comment] 2018-08-26 13:00
Do you have any domain configured or you access it by IP?

**Comment by oscartbeaumont** [comment] 2018-08-26 13:07
IP. I am currently updating Docker on a second system and I will try running the server there and see if it works.

**Comment by oscartbeaumont** [comment] 2018-08-26 13:32
It works when hosted on another machine. So I am going to reinstall it to my server and see if that fixes it.

**Comment by mprasil** [comment] 2018-08-26 13:36
Make sure you pull the latest image!

**Comment by oscartbeaumont** [comment] 2018-08-26 14:07
I repulled the image from docker and it still didn't work but I created a new VM (Cloned from a base Image), installed docker and it didn't work. My server is running Debian and that could be causing an issue or my base vm has something it doesn't like or it does like being run inside a vm but docker has been working fine for other stuff.

**Comment by mprasil** [comment] 2018-08-26 15:08
Seems very unlikely that host OS would affect web interface in such way. Maybe a different docker version? (even that sounds kinda unlikely) I tried couple different setups here and failed to reproduce your issue. :confused:

**Comment by Haxy89** [comment] 2018-08-27 07:09
I had the same problem on Google Chrome, after switch to Firefox problem gone. I wrote about it here

**Comment by mprasil** [comment] 2018-08-27 12:29
Hi, I've built `mprasil/bitwarden:beta` which is using latest Vault from master. Can you test that one and see if you still get any issues?

**Comment by oscartbeaumont** [comment] 2018-08-27 13:36
I installed the beta container and am getting the error on the account signing up page and submitting a correct login page. The login had to b created through Safari which isn't suffering this bug.

**Comment by mprasil** [comment] 2018-08-27 13:39
What web request does it make when trying to log in?

**Comment by oscartbeaumont** [comment] 2018-08-27 13:42
`POST /api/accounts/prelogin`
It Returned:
`{"Kdf":0,"KdfIterations":5000}`

**Comment by theazriel** [comment] 2018-08-27 16:50
hi,
this issue looks only a chrome browser, with edge it works fine.

in chrome i get the follow issue: 

This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.

11core.js:1440 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'importKey' of null
TypeError: Cannot read property 'importKey' of null
  at n.<anonymous> (webCryptoFunction.service.ts:45)
    at zohoVaultCsvImporter.ts:7
    at Object.next (zohoVaultCsvImporter.ts:7)
    at zohoVaultCsvImporter.ts:7
    at new t (zone.js:887)
    at t (zohoVaultCsvImporter.ts:7)
......

**Comment by Silveress** [comment] 2018-08-28 08:43
Same thing was happening for me on 2.2.0.
Upgraded to 2.2.1 and its still happening.

This is a clean install as well (just started testing it for my purporses)

**Comment by mprasil** [comment] 2018-08-28 09:31
@Silveress, can you confirm, that this happens only in Chrome for you?

**Comment by oscartbeaumont** [comment] 2018-08-28 11:37
I just setup my bitwarden_rs on a testing subdomain so I could share it and see if that can help with debugging but after setting that up I noticed it was working. My server parses traffic through an Nginx Proxy which handles HTTPS termination automatically. I them tired setting the DOMAIN env variable and that didn't help. So I generated a self signed HTTPS cert and configured it with the ROCKET_TLS env variable and the issue when away. So it must be something to do with HTTP.

**Comment by Silveress** [comment] 2018-08-28 12:42
I can concur with @oscartbeaumont.

I set it up on a subdomain on my vps with letsencrypt certs and nginx reverse proxy.
Accessing it via the sub domain it worked perfectly.
Accessing directly via IP (no cert) and the issues returned.

And these issues only pop up on chrome (and chromium) so I presume it is something how chrom(ium) handles http sites.

**Comment by theazriel** [comment] 2018-08-28 13:34
I have create an account without https/ssl  with edge browser an linked this ip from docker 0.0.0.0.8080 to the Bitwarden app, it work fine nur you must Change from https into http, so you habe Access from all devices on your own bitwarden

**Comment by oscartbeaumont** [comment] 2018-08-28 13:56
@theazriel From my understanding this only effects Chromes and that is why Edge and Safari are not effected.

**Comment by theazriel** [comment] 2018-08-28 14:05
Yes correct, this is only a Chrome Problem, after Changing Browser everything works fine

**Comment by mprasil** [comment] 2018-08-28 14:15
@oscartbeaumont do you think it would make sense to report this issue in the upstream Vault repo? Is there anything that can be done about this?

**Comment by CaptInsano** [comment] 2018-08-31 18:26
Just to add, same problem here.

Currently running most recent docker image at time of writing: mprasil/bitwarden:latest 31/08/18

Chrome Version 68.0.3440.106 (Official Build) (64-bit) not allowing login or creation of new user, Firefox works perfectly.

**Comment by mprasil** [comment] 2018-08-31 22:56
I've reported it upstream to bring some awareness about this problem.

**Comment by mprasil** [comment] 2018-08-31 23:00
@CaptInsano I'm using Bitwarden with LetsEncrypt cert on reverse proxy and it works fine everywhere including Chrome. I can only reproduce the problem over HTTP, is it possible there are some other issues affecting your HTTPS connection? So far everyone reported, that it works for them over secure channel.

**Comment by mprasil** [comment] 2018-09-01 07:15
Confirmed with Kyle, that this is [intentional](https://github.com/bitwarden/web/issues/254), we need to document this to avoid people reporting it as a bug.

**Comment by mprasil** [comment] 2018-09-03 11:56
The documentation was merged. I'm going to resolve this as wontfix, because it's just not supported upstream.

**Closed by mprasil** 2018-09-03 11:56 UTC
Labels: documentation

**Comment by CorneliousJD** [comment] 2019-01-08 20:08
Just dropping in for early 2019 to say that I just deployed this on unRAID docker container and since there's no way to access over HTTPS out of the box without setting up reverse proxy, it fails in Chrome to let you sign in or register a new user. Firefox and Edge worked fine. 

Can you couple this with at least a way to access over HTTPS? Even if it's just a self-signed cert so users can at least get accounts created and then setup their own reverse proxy if they want to secure it? 

FYI I almost decided to ditch this assuming it would NEVER work in Chrome, but sounds like once I reverse proxy it, it'll be fine. Working on that next.

**Comment by CorneliousJD** [comment] 2019-01-08 21:02
@dani-garcia  - sounds good, With a quick bit of research I was able to solve the problem and I'm up and running with a super lightweight self-hosted option. Thanks for the hard work on this!

**Comment by hank** [comment] 2019-04-20 19:56
Yeah another user here that ran into this. Could you make it so a warning or something pops up when this occurs? It's hard to figure out that you need HTTPS.

**Comment by mprasil** [comment] 2019-04-20 20:22
I think this should probably be implemented/reported upstream as it's client only issue?

**Comment by dani-garcia** [comment] 2019-04-20 20:24
As far as I know upstream doesn't support HTTP at all, so I don't think it's of much use. I think it would be useful to include a warning somewhere, as the error message is quite cryptic, not sure if modifying the web vault is the best way though.

**Comment by mprasil** [comment] 2019-04-20 20:33
Ah right, I forgot they don't support it at all. I wonder if they'd accept PR with some user friendly error message anyways.

**Comment by ngloom** [comment] 2020-06-23 02:30
in my case , error disappear after using https

**Comment by briceparmentier** [comment] 2020-09-14 12:04
Hi there,
I'm facing the same issue, knowing that in my case I'm self-hosting it on a Raspberry PI.
It appears the same on several browsers, Firefox at home, Chrome and Edge at work.
On Chrome or Firefox, nothing happens at all, on Edge, I get kind of a red popup on the right side telling something went wrong (and nothing else).
I'm not using HTTPS, maybe that's the clue?
Thanks !

**Comment by meyerje** [comment] 2020-09-14 12:13
Use https @briceparmentier

**Comment by briceparmentier** [comment] 2020-09-15 08:01
> Use https @briceparmentier

@meyerje I've been reading the Wiki here https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS, which points to another page for how to create a personal certificate. It also say that "_If following that guide your ROCKET_TLS line could look like this: -e ROCKET_TLS='{certs="/ssl/bitwarden.crt",key="/ssl/bitwarden.key"}' \_", but I'm missing the part of where to move the generated files (all certificates and keys and all the stuff from the second page) to the docker machine...
Anyone can help with this?
Thanks
