### ISSUE TITLE
Sign up after invitation is broken

### ISSUE THREAD

**Issue by paradeiser** [dani-garcia/bitwarden_rs#920] opened 2020-03-19 18:13 UTC
### It's not possible to create account after invitation
my variables are
```
  "signups_allowed": false,
  "invitations_allowed": true,
```
hence: Public signups are disallowed, but invited email addresses are able to create an account.
Before the latest update all worked as expected - no changes to setup since then.
Behaviour as expected when using vault.bitwarden.com

### My environment

* Bitwarden_rs version: 1.14-2ee07ea1

* Install method: Synology Docker

### Steps to reproduce

1. A logged in user invites a new user to an organisation
2. Invited user clicks button "Join Organization Now" in invitation mail
3. Bitwarden website pops up, hit the button "Create Account"

### Expected behaviour

4. Usually a form would show up, asking for name, master-password, hint, etc.

### Actual behaviour

4. The usual form pops up just for a second, then user gets kicked to log-in page with error

> "Logged out - Session expired"

<img width="317" alt="Bildschirmfoto 2020-03-19 um 18 38 22" src="https://user-images.githubusercontent.com/43011936/77100161-7bacc880-6a15-11ea-88e3-88e6a298162e.png">

tried different browsers, cleared all cookies and browser-data; restarted docker.

**Comment by BlackDex** [comment] 2020-03-19 21:00
I think this will be fixed with the latest build based upon the latest commit which is not build as of yet.

I can't check at this moment if that is the case, but if i check the link it uses it should.

**Comment by BlackDex** [comment] 2020-03-19 21:49
Well just tested it. Doesn't solve it. So this is something else.

**Comment by Stiefmeister** [comment] 2020-03-20 05:58
Got the same problem - first thought it had something to do with my reverse proxy setup (letsenrcrypt); but behavior is the same locally. Tried different browsers as well, no luck

**Comment by BlackDex** [comment] 2020-03-20 07:34
This has something to do with the new policies in the latest web-vault 2.13.1.

**Comment by Stiefmeister** [comment] 2020-03-20 09:20
Had a look at the logs, seems some kind of access token is expected for invited users!?

[2020-03-20 09:32:34][request][INFO] GET /api/organizations/_/policies/token?token=#################
[2020-03-20 09:32:34][auth][ERROR] Unauthorized Error: No access token provided
[2020-03-20 09:32:34][response][INFO] GET /api/organizations/<org_id>/policies/<pol_type> (get_policy) => 401 Unauthorized

**Comment by BlackDex** [comment] 2020-03-20 09:40
Yea, we found what the issue is.
This is because of the new policy rules which are available in the latest web-vault.
There you can enforce specific password policies etc.. 
That is what is breaking the invites now.

**Comment by BlackDex** [comment] 2020-03-20 09:43
btw. you can workaround this by using an older web-vault which does not have this.
You need to download https://github.com/dani-garcia/bw_web_builds/releases/tag/v2.12.0e extract it in a specific folder in your data folder. And then configure bitwarden_rs via the `WEB_VAULT_FOLDER` env variable to use that specific folder.

**Comment by paradeiser** [comment] 2020-03-20 09:50
Thanks!
Is there an ETA for a release that fixes this bug?

**Comment by BlackDex** [comment] 2020-03-20 10:12
Fix is committed, now we have to wait for the all mighty docker hub to finish the new build.

**Comment by Stiefmeister** [comment] 2020-03-20 10:33
> 
> 
> Fix is committed, now we have to wait for the all mighty docker hub to finish the new build.

Thanks for the swift fix/ support!

**Comment by paradeiser** [comment] 2020-03-20 10:51
superb! merci and thanks a lot!

**Comment by paradeiser** [comment] 2020-03-20 18:03
I can confirm: latest build is up and fixed the issue. Thanks a lot!

**Comment by dani-garcia** [comment] 2020-03-21 18:31
This should be fixed now in 1.14.1, but it might take some hours for the docker images to build still.

**Closed by dani-garcia** 2020-03-21 18:31 UTC

**Comment by samgaw58** [comment] 2021-05-28 18:51
I am running Vaultwarden V1.21.1 on Portainer and I am getting the same error. If I invite a new user, click the email link and then click create account I get the same error that the user already exists.
Is there any workaround I can do?

**Comment by samgaw58** [comment] 2021-05-28 19:05
Here are the last three lines of the logs

[2021-05-28 19:02:35.196][request][INFO] POST /api/accounts/register

[2021-05-28 19:02:35.196][vaultwarden::api::core::accounts][ERROR] User already exists

[2021-05-28 19:02:35.196][response][INFO] POST /api/accounts/register (register) => 400 Bad Request
