### ISSUE TITLE
Unable to delete folders in the web vault

### ISSUE THREAD

**Issue by magiruuvelvet** [dani-garcia/bitwarden_rs#446] opened 2019-03-26 20:51 UTC
I'm unable to delete (empty) folders in the web vault. Clicking on the delete button does nothing at all, no message in console and no requests to the server.

I manually need to delete them from the `folders` table in the SQLite database and restart the server to get rid of unused folders. Renaming works though.

Is there a way to debug this properly? Logging is enabled, but no logfile is ever being created.

I'm running bitwarden_rs from the docker image; registration is disabled, websockets are disabled.

Tried browsers:
 - Waterfox
 - Vivaldi Browser

**Comment by dani-garcia** [comment] 2019-03-26 22:54
I just tried deleting a newly created empty folder and it works for me. Can you reproduce this from a new  user? The steps I followed are: create folder from the plus icon in the left sidebar, select folder from the same sidebar, click pencil icon and then the trashcan in the popup.

If you don't get anything in the browser's console and no request is made, I'm not sure how to debug it otherwise.

**Comment by magiruuvelvet** [comment] 2019-03-27 05:08
I still couldn't delete any folders, and now I also can't delete the newly created test user within an organization. I managed to get something in the browser log. Maybe my reverse proxy is not configured probably. I also checked my firewall rules and there seems to be a major f\*ckup blocking the container network.

![スクリーンショット_20190327_060447](https://user-images.githubusercontent.com/13280758/55051688-8cbb3780-5056-11e9-9377-8e81e2acc274.png)

I disabled the firewall, but still got the same error in both browsers.

**Comment by mprasil** [comment] 2019-03-27 13:37
Try to disable websocket if you have it enabled. (`WEBSOCKET_ENABLED=false`) If your proxy isn't configured properly, but the client thinks that it should use websocket, it tends to misbehave in weird ways.

**Comment by magiruuvelvet** [comment] 2019-03-27 17:52
I have websockets disabled already. Than my only other guess could be the reverse proxy. I'm using Caddy server with the `transparent` setting.

It's not that kind of a hassle, when it works with the 3rd browser. It's not like I need to regularly delete folders :smile: All other parts of the web vault works in the other two browsers.

**Comment by mprasil** [comment] 2019-03-28 11:02
Can you share your config maybe? Redact the secret parts. Is it similar to [this one](https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples#caddy)?

**Comment by magiruuvelvet** [comment] 2019-03-28 11:42
this is my Caddy config file with websockets disabled

```caddyfile
mydomain {
    tls myemail

    proxy / http://172.18.92.5:80 {
        transparent
    }
}
```

**Comment by mprasil** [comment] 2019-03-28 12:51
This is kinda long stretch, but do the folders contain any special characters? Also did you try to disable all browser addons?

**Comment by magiruuvelvet** [comment] 2019-03-28 16:38
The name doesn't matter, fails with Unicode and ASCII equally. It indeed works without extensions, which I figured already that some extension is blocking something somewhere.

I have all kinds of security related extensions installed and one of them may act way too paranoid on the web vault.

**Comment by XelNika** [comment] 2019-03-30 14:32
I had this issue today and found that the deletion modal is being blocked by one of my uBlock Origin lists.

![Screenshot_20190330_152357](https://user-images.githubusercontent.com/14213514/55277461-daf36380-5300-11e9-95bc-54db6b81c7e6.png)

To fix this, add your own filter to uBO:

    [your-bitwardenrs-address]#@#.swal-overlay--show-modal.swal-overlay

**Comment by magiruuvelvet** [comment] 2019-03-30 16:16
@XelNika Thanks, that did the trick and the popup now appears.

**Comment by mprasil** [comment] 2019-04-10 10:19
I think this was resolved thanks to @XelNika suggestion, I'm going to close this, but feel free to reopen if there's still some issue regarding this.

**Closed by mprasil** 2019-04-10 10:19 UTC
