### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by joe217** [dani-garcia/bitwarden_rs#212] opened 2018-10-06 18:18 UTC
Hi, 

Any thoughts on getting the admin panel working?

Usually accessible at my.bitwardendomain.com/admin?

**Comment by fbartels** [comment] 2018-10-06 19:14
I think that has been previously discussed at https://github.com/dani-garcia/bitwarden_rs/issues/202

**Comment by mprasil** [comment] 2018-10-06 19:58
Yeah, there actually isn't much we could use from upstream in this case and generally is too much work for little benefit. If there's something specific you'd like to do in it, it's usually easy enough to do directly with sqlite client on the db.

Feel free to ask if you want to do something specific.

I'm closing this as duplicate of #202

**Closed by mprasil** 2018-10-06 19:58 UTC

**Comment by joe217** [comment] 2018-10-08 22:31
Thank you for the prompt response...and my apologies for missing the recent similar post.

Two quick follow-up quesitons:
1. Isn't the database encrypted?  How would I list the user names?
2. If the user names are unencrypted, could you list a sample CLI command that I could use to list them?  I tried doing some research on sqlite, but may be a bit above my head.  A few simple commands may point me in the right direction for making the actual bash scripts...

Thanks!

**Comment by fbartels** [comment] 2018-10-09 05:09
@joe217 the linked ticket has this example: `sqlite3 data/db.sqlite3 "select * from users;"`

**Comment by joe217** [comment] 2018-10-09 05:15
Ok. Thank you. Figured that out now. That produces mostly gibberish,
though. The username emails are in plaintext. How would I go about deleted
them?

Also, would working on the bw-data file be equivalent to working in the
actual container?

Thanks.

**Comment by fbartels** [comment] 2018-10-09 07:44
You can find a comprehensive tutorial on sqlite at https://www.tutorialspoint.com/sqlite/

The reason for the "gibberish" is that it outputs all the data in the table. Looking at it a bit closer you the following probably give a more meaningful output `sqlite3 data/db.sqlite3 "select uuid,email from users;"`

In the end you probably want something like: `sqlite3 data/db.sqlite3 "delete from user where email='bla@company';"` (untested)

**Comment by mprasil** [comment] 2018-10-09 08:09
Careful with the deletes though, the user has a lot of attached objects in the DB. The best thing to do would be to change his password to some string like "deactivated" or something like that. This will never match the hashed passphrase and will effectively disable the account.

**Comment by joe217** [comment] 2018-10-11 03:10
https://github.com/dani-garcia/bitwarden_rs/issues/212#issuecomment-428093496

`sqlite3 data/db.sqlite3 "select uuid,email from users;"

So the above does produce a very organized list of users.  But best not to delete?  If I want to change the password, how to do that?  Can that same email ever be used again - after changing the password?  I would suspect no?

**Comment by dani-garcia** [comment] 2018-10-11 14:28
This should disable the user and free the email to be used again:
```
sqlite3 data/db.sqlite3 "update users set email='disabled1', key='', private_key='', public_key='' where email='old@mail';"
```
Note: the 'disabled1' value could be anything, I just used that to make sure it wouldn't clash with a real email address.

The email is used when calculating the password hash at login by the client, which means it couldn't be possible to login again after that command. The command also deletes the users encryption keys for good measure.

The problem with deleting users is that there isn't currently any method to delete all the data assotiated with them unless you can login as the user yourself (In which case you can use the web vault option).
