### ISSUE TITLE
Vault empty; No longer Part of Organisations 

### ISSUE THREAD

**Issue by davidh2k** [dani-garcia/bitwarden_rs#559] opened 2019-08-07 09:10 UTC
I have an issue, when I log into the webinterface (or any new remote client) I have an empty Vault, it even states that I'm no longer part of any of my two organisations.

![image](https://user-images.githubusercontent.com/6970146/62609628-6c539180-b902-11e9-969c-a577f12db4c7.png)

However, if i look at the admin panel, it still shows my belonging to the two organisations:

![image](https://user-images.githubusercontent.com/6970146/62610243-978ab080-b903-11e9-9a9c-790ce5fd6166.png)

I already did a backup of my still synched desktop client that had the passwords still. Any ideas how my vault can be empty? Could that hapenned on a container update?

**Comment by davidh2k** [comment] 2019-08-07 09:16
For Sanity checking I just added one dummy password and both restarted and --force-recreate'd the container via docker-compose - dummy password still there.

**Comment by davidh2k** [comment] 2019-08-07 10:59
`[2019-08-07 10:56:11][rocket::rocket][INFO] GET / text/html:
[2019-08-07 10:56:11][_][INFO] Matched: GET / (web_index)
[2019-08-07 10:56:11][_][INFO] Outcome: Success
[2019-08-07 10:56:11][_][INFO] Response succeeded.
[2019-08-07 10:56:19][rocket::rocket][INFO] POST /api/accounts/prelogin application/json; charset=utf-8:
[2019-08-07 10:56:19][_][INFO] Matched: POST /api/accounts/prelogin (prelogin)
[2019-08-07 10:56:19][_][INFO] Outcome: Success
[2019-08-07 10:56:19][_][INFO] Response succeeded.
[2019-08-07 10:56:19][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded; charset=utf-8:
[2019-08-07 10:56:19][_][INFO] Matched: POST /identity/connect/token (login)
[2019-08-07 10:56:19][bitwarden_rs::error][ERROR] JsonError. {"TwoFactorProviders":[0],"TwoFactorProviders2":{"0":null},"error":"invalid_grant","error_description":"Two factor required."}
[2019-08-07 10:56:19][_][INFO] Outcome: Success
[2019-08-07 10:56:19][_][INFO] Response succeeded.
[2019-08-07 10:56:33][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded; charset=utf-8:
[2019-08-07 10:56:33][_][INFO] Matched: POST /identity/connect/token (login)
[2019-08-07 10:56:33][bitwarden_rs::api::identity][INFO] User user@mail.domain logged in successfully. IP: 62.176.232.167
[2019-08-07 10:56:33][_][INFO] Outcome: Success
[2019-08-07 10:56:33][_][INFO] Response succeeded.
[2019-08-07 10:56:33][rocket::rocket][INFO] POST /notifications/hub/negotiate text/plain; charset=UTF-8:
[2019-08-07 10:56:33][_][INFO] Matched: POST /notifications/hub/negotiate (negotiate)
[2019-08-07 10:56:33][_][INFO] Outcome: Success
[2019-08-07 10:56:33][_][INFO] Response succeeded.
[2019-08-07 10:56:33][rocket::rocket][INFO] GET /api/sync?excludeDomains=true application/json:
[2019-08-07 10:56:33][_][INFO] Matched: GET /api/sync?<data..> (sync)
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error("EOF while parsing a value", line: 1, column: 0)', src/libcore/result.rs:997:5
[2019-08-07 10:56:33][ws::io][INFO] Accepted a new tcp connection from 172.19.0.4:48452.
[2019-08-07 10:56:33][bitwarden_rs::api::notifications][INFO] Server got message '{"protocol":"messagepack","version":1}'.
`

Maybe this is in any way related to https://github.com/dani-garcia/bitwarden_rs/issues/494 ?

**Comment by davidh2k** [comment] 2019-08-07 11:09
I just _kinda_ solved it by pulling the current image and switching from version:

> /--------------------------------------------------------------------\
> |                       Starting Bitwarden_RS                        |
> |                       Version 1.8.0-f25ab42e                       |
> |--------------------------------------------------------------------|
> | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
> | official channels to report bugs/features, regardless of client.   |
> | Report URL: https://github.com/dani-garcia/bitwarden_rs/issues/new |
> \--------------------------------------------------------------------/

to:

/--------------------------------------------------------------------\
|                       Starting Bitwarden_RS                        |
|                       Version 1.9.1-8be2ed62                       |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Report URL: https://github.com/dani-garcia/bitwarden_rs/issues/new |
\--------------------------------------------------------------------/

Log now shows:

> [2019-08-07 11:05:09][rocket::rocket][INFO] POST /api/accounts/prelogin application/json; charset=utf-8:
> [2019-08-07 11:05:09][_][INFO] Matched: POST /api/accounts/prelogin (prelogin)
> [2019-08-07 11:05:09][_][INFO] Outcome: Success
> [2019-08-07 11:05:09][_][INFO] Response succeeded.
> [2019-08-07 11:05:09][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded; charset=utf-8:
> [2019-08-07 11:05:09][_][INFO] Matched: POST /identity/connect/token (login)
> [2019-08-07 11:05:09][bitwarden_rs::error][ERROR] JsonError. {"TwoFactorProviders":[0],"TwoFactorProviders2":{"0":null},"error":"invalid_grant","error_description":"Two factor required."}
> [2019-08-07 11:05:09][_][INFO] Outcome: Success
> [2019-08-07 11:05:09][_][INFO] Response succeeded.
> [2019-08-07 11:05:16][rocket::rocket][INFO] POST /identity/connect/token application/x-www-form-urlencoded; charset=utf-8:
> [2019-08-07 11:05:16][_][INFO] Matched: POST /identity/connect/token (login)
> [2019-08-07 11:05:16][bitwarden_rs::api::identity][INFO] User davidh1990@gmx.de logged in successfully. IP: 62.176.232.167
> [2019-08-07 11:05:16][_][INFO] Outcome: Success
> [2019-08-07 11:05:16][_][INFO] Response succeeded.
> [2019-08-07 11:05:16][rocket::rocket][INFO] POST /notifications/hub/negotiate text/plain; charset=UTF-8:
> [2019-08-07 11:05:16][_][INFO] Matched: POST /notifications/hub/negotiate (negotiate)
> [2019-08-07 11:05:16][_][INFO] Outcome: Success
> [2019-08-07 11:05:16][_][INFO] Response succeeded.
> [2019-08-07 11:05:16][rocket::rocket][INFO] GET /api/sync?excludeDomains=true application/json:
> [2019-08-07 11:05:16][_][INFO] Matched: GET /api/sync?<data..> (sync)
> [2019-08-07 11:05:16][_][INFO] Outcome: Success
> [2019-08-07 11:05:16][_][INFO] Response succeeded.
> [2019-08-07 11:05:16][ws::io][INFO] Accepted a new tcp connection from 172.19.0.4:48578.
> [2019-08-07 11:05:16][bitwarden_rs::api::notifications][INFO] Server got message '{"protocol":"messagepack","version":1}'.

And Webinterface shows all passwords and organisations again. So in fact maybe really related to #494 ?

Solved for the moment, but worth investigating more?

**Comment by mprasil** [comment] 2019-08-10 20:47
The previous version you used was quite old. It's still strange that it was failing this way, but not sure how we can troubleshoot further unless you have some way to reproduce it again.

If it ever happens again, one thing worth trying is to log out the user, force-reload the interface (ctrl-shift-r) and log in again.

**Comment by jamestutton** [comment] 2019-09-05 08:05
Can confirm I am experiencing a similar issue.  In my case I created a new org owner and the downgraded the original owner to a "User" permissons didnt seem to update correctly so remove the user and readded and now they cant see the org at all.  Will see if i can replicate in a test env and update.

**Comment by jamestutton** [comment] 2019-09-05 09:02
Sorry not sure where this issue was coming from.  Not able to recreate with current version.  And when pointed the latest docker image at my original data the issue went away. So can only assume what ever was the cause has been fixed.

**Comment by mprasil** [comment] 2019-10-11 10:08
Closing this now, but feel free to reopen if you can find some way to reproduce the problem.

**Closed by mprasil** 2019-10-11 10:08 UTC
