### ISSUE TITLE
podman error on running bitwardenrs/server:latest

### ISSUE THREAD

**Issue by gnu300** [dani-garcia/bitwarden_rs#718] opened 2019-11-12 13:58 UTC
Since Fedora 31 defaults to cgroupv2 [1] podman is one of the recommended alternatives. Unfortunately podman can't run bitwarden_rs:

```
[gnu300@fuso container]$ docker run -d --name bitwarden -v /bw-data/:/data/ -p 8888:80 bitwardenrs/server:latest
Trying to pull docker.io/bitwardenrs/server:latest...
Getting image source signatures
Copying blob de171338eba4 done
Copying blob 3332f6a74903 done
Copying blob 4f3b3bfff359 done
Copying blob 68c6b84d8d28 done
Copying blob 8d691f585fa8 done
Copying blob 35e7083657ef done
Copying blob fcb7d34ccc30 done
Copying config 97d8cc3df2 done
Writing manifest to image destination
Storing signatures
Error: executable file not found in $PATH: No such file or directory: OCI runtime command not found error
```

In order to get the container running with podman you'll have to change:
`CMD ["./bitwarden_rs"]`
to
`CMD ./bitwarden_rs`

Tested on Fedora 31 with podman version:
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.13.1
OS/Arch:            linux/amd64

[1] https://www.redhat.com/sysadmin/fedora-31-control-group-v2

**Comment by mprasil** [comment] 2019-11-13 09:44
Exec form of specifying `CMD` is actually preferred according to official documentation. But maybe a slightly cleaner approach would be to set `WORKDIR /` and `CMD ["/bitwarden_rs"]`. (note the removed dot to make the path absolute)

I can't reproduce your issue on my system, can you test above changes?

**Comment by gnu300** [comment] 2019-11-13 12:47
With the suggested changes i am able to build and run the container with podman. Here is the PR for it. #720 

Thanks!

**Comment by mprasil** [comment] 2019-11-13 21:22
I think we can close this with PR almost out of the door. Thanks for working on this and thanks for finally giving me good reason to install podman. :smile:

**Closed by mprasil** 2019-11-13 21:22 UTC
