### ISSUE TITLE
Editing an item, further down the list, in web vault causes the page to revert back to a previous spot

### ISSUE THREAD

**Issue by slaughtermouse** [dani-garcia/bitwarden_rs#878] opened 2020-02-26 05:29 UTC
### Subject of the issue
Editing an item, further down the list, in web vault causes the page to revert back to a previous spot. That is if I'm editing an item, that begins with T and click save the page returns to the page back to items beginning with P. 

I'm then not able to scroll down anymore, and have to refresh the vault and sign in again.

I couldn't replicate this on https://vault.bitwarden.com/

### Your environment

* Bitwarden_rs version: 1.13.1-cd890754

* Install method: Docker
* Clients used: Web vault
* Reverse proxy and version: Traefik 2.1.4
* Other relevant information: Happens in Chrome and Firefox on Mac OS and Widows 10

### Steps to reproduce
1. Browse to https://bitwarden.domain.tld
2. Scroll down ensuring the page refreshes with more items
3. Edit an item, click save

### Expected behaviour
1. Web vault returns to same spot in web page

### Actual behaviour
1. Web vault returns to previous spot, and I'm unable to scroll down to reveal anything past the last item beginning with P

### Relevant logs
Screenshots attached:
<img width="1474" alt="Editing item beginning with T" src="https://user-images.githubusercontent.com/14948829/75315116-a5ffe000-58c6-11ea-9da3-9161b88640db.png">

Upon clicking save I'm taken back to here:
<img width="1477" alt="Page returns to items beginning with P" src="https://user-images.githubusercontent.com/14948829/75314877-e6129300-58c5-11ea-9410-e7b4657cb51c.png">

**Comment by mqus** [comment] 2020-02-26 07:34
Which vault version do you have or which docker image did you use?

**Comment by slaughtermouse** [comment] 2020-02-26 09:05
Vault version:  2.12.1
Image: bitwardenrs/server:latest

**Comment by BlackDex** [comment] 2020-02-26 10:10
Please report this upstream https://github.com/bitwarden/web/issues since bitwarden_rs only uses the web-vault code and does not maintain it.

**Comment by jjlin** [comment] 2020-02-26 14:31
He said it's not reproducible on https://vault.bitwarden.com/, though. I can confirm the same behavior (jump back occurs on bitwarden_rs web vault, doesn't on vault.bitwarden.com). I'm running the latest `alpine` image (eb72b46ed172).

**Comment by slaughtermouse** [comment] 2020-02-26 20:49
Yeah, I couldn't replicate the problem on https://vault.bitwarden.com hence opting to log here

I feel that if I raise an issue with them, pointing out I use bitwarden_rs, they'll probably tell me to raise an issue here

**Comment by BlackDex** [comment] 2020-02-26 20:53
Well, the author of bitwarden knows that bitwarden_rs just uses the web-vault, with some small tweaks. But still lets test it here first. I will try to do some testing also and see if i can reproduce and track down the error.

**Comment by slaughtermouse** [comment] 2020-02-26 20:55
Ok thanks, otherwise let me know and I'll raise an issue there

**Comment by BlackDex** [comment] 2020-02-27 10:45
For some reason i see that the rs version is doing both a PUT and a GET while the official one is only doing a PUT and nothing more. Lets see if i can figure out why.

**Comment by BlackDex** [comment] 2020-02-27 11:16
Ok, this seems to be a web-socket thing.
When i manually run the PUT command via a curl cli command i see a GET request in the browser, though, this does NOT reload my browser at that point.

**Comment by BlackDex** [comment] 2020-02-27 13:09
Oke. The strange thing here is that i can not reproduce it on my dev environment.
First i thought, well maybe because i directly connect to it locally, so no proxy etc.. in between.
Then i tested it with nginx and https in front of it but also then this does not happen.
I have tried the latest web v2.12.0d (v2.12.1) and a custom build with from the master of bitwarden/web on both my local dev and remote production environment.

I can only reproduce it on the docker build environment and **not** with my dev environment.
Even with an other web-vault to rule out an issue there.

I have at this point really no clue.
@jjlin Could you test it on your dev environment also?

btw, i have not tested a new docker build.

**Comment by slaughtermouse** [comment] 2020-02-27 21:40
Sounds like a bit of a weird one :|

Thanks for testing out the various scenarios

**Comment by BlackDex** [comment] 2020-03-01 21:59
@dani-garcia or @mprasil or anyone else. Can someone confirm this?

**Comment by BlackDex** [comment] 2020-03-15 09:03
@slaughtermouse could you try to update to the latest version? The latest docker build includes the v2.13.1 web vault. And at least on my mobile I'm not experiencing the issue anymore.

**Comment by slaughtermouse** [comment] 2020-03-16 07:25
@BlackDex, sorry I actually ended up moving back to 1password. There were a few too many niggles with bitwarden that made it annoying to use vs 1password.

If it's working for you I'm happy to close, though @jjlin might be able to confirm seeing as they were able to reproduce as well

**Comment by BlackDex** [comment] 2020-03-16 08:13
@slaughtermouse Sorry to read.

May i ask which niggles? Maybe if there are items we can fix or improve i would like to know about them so that we can try and improve those.

I just tested it my self on the docker build environment with firefox, but i refreshes there also.

**Comment by slaughtermouse** [comment] 2020-03-16 08:46
Just small things, like if you have multiple accounts on a website e.g. Office365 or GSuite it just enters the last used username/password. You can bring up the extension with ctrl+shift+l but then you can't even use arrow keys to navigate to an item..

No trash can, so accidental deletes are lost forever. Though I see this is finally being "planned"

Plus a few other things that are already feature requests: https://community.bitwarden.com/c/feature-requests/5/l/latest?order=votes

Of which there seems to be minimal to no developer interaction on the forums, so its hard to know what/if anything is actually being done

This is by no means a post to bash bitwarden, just reasons why I went back to 1password

**Comment by BlackDex** [comment] 2020-03-16 16:15
Non taken. And all is stuff we can not change.
You should use what fits the best for you, that is the nice thing about all these different services.

**Comment by slaughtermouse** [comment] 2020-03-16 21:58
Agreed, and I'll be keeping an eye out periodically to check on progress

**Comment by BlackDex** [comment] 2020-03-17 09:47
Well, i did some more testing yesterday.
And it seems it has something to do with the vault data.

When using a clean vault, and only personal items, it will not reload.
When i use my private real vault data, which has folders and orgs i'm refreshed.
So it has something to do with that, and probably is an upstream bug.

I Will try to debug it further when i can.

**Comment by BlackDex** [comment] 2020-03-17 11:08
Well the issue seems to be attachments.
If you have one item which has an attachment, it will cause this.
Removing the attachment again and it is fixed.

**Comment by BlackDex** [comment] 2020-03-18 19:28
Upstream has been able to reproduce the issue and will take a look at it.

**Comment by jjlin** [comment] 2020-03-18 19:52
> Well the issue seems to be attachments.
> If you have one item which has an attachment, it will cause this.
> Removing the attachment again and it is fixed.

Just FYI, I don't think it's exclusively related to attachments. I could reproduce the issue with my normal vault data, and I don't use attachments at all.

**Comment by BlackDex** [comment] 2020-03-18 20:12
Well, i was only able to have it appear when i had an attachment in one item. Maybe if there is a note or a card? If you have more insight then update the upstream issue.

**Comment by BlackDex** [comment] 2020-10-09 21:27
Going to close this one as it's not something we can fix in this repo.

**Closed by BlackDex** 2020-10-09 21:27 UTC
