### ISSUE TITLE
What's the purpose of Verify Email?

### ISSUE THREAD

**Issue by pdarcos** [dani-garcia/bitwarden_rs#793] opened 2020-01-01 18:14 UTC
Hi guys,

I noticed the verify email message is present when you first log in, but I don't see what the purpose is for this in bitwarden_rs

"Verify your account's email address to unlock access to all features"

Is this a leftover from bitwarden? What other features are there?

Thanks

**Comment by Zauberfisch** [comment] 2020-01-02 02:31
My initial guess was that the "send me my masterpassword hint" feature would only send you an email if your email address is confirmed. Same for "new login from ...." notifications.

But I just tested that, and that's not the case. Unconfirmed accounts still get both types of emails.

I think keeping the confirmation of emails makes sense, because of the 2 reasons above. And the email sending part should be fixed to only send emails to confirmed addresses.

**Comment by mprasil** [comment] 2020-01-02 07:41
I think the initial motivation was to have that in place together with domain whitelist so that users won't be able to log in until they verify they own email matching the whitelist.

**Comment by BlackDex** [comment] 2020-01-03 10:46
It can also be a special check for the admins to maybe force ppl to verify there e-mail within x hours or so. That is something we could create if we wanted.

I can't remember features not working when not verified in the official self-hosted or cloud version. But not sure.

**Comment by tomuta** [comment] 2020-01-05 20:59
> I think the initial motivation was to have that in place together with domain whitelist so that users won't be able to log in until they verify they own email matching the whitelist.

Well, that might be a bitwarden_rs-only enhancement. The `SIGNUPS_DOMAINS_WHITELIST` list in combination with `SIGNUPS_VERIFY=true` and `SIGNUPS_ALLOWED=true` allows an organization to create/delete accounts with e.g. their corporate email address so long they have access to their emails. This also prevents them from impersonating someone else (though that would pose little harm).

The "stock" email verification however actually serves another purpose: It prevents someone else from deleting your account pretending to have lost the password. If you create an account and either mistyped your email address or you do not remember your password, and you also haven't verified your email, then you (or anyone else) can actually delete that account instantly. This way you can re-create your account with the correct email address, or with the correct master password. However, if you want to prevent others from doing this, then you need to verify your email after creating the account. This is because the bitwarden model doesn't require upfront email verification, accounts instantly work after creating them. A slight deviation from that model is setting `SIGNUPS_VERIFY=true`, in which case email verification is forced after creating the account and before being able to log in, which eliminates these drawbacks (but feels like it's shoe-horned into the stock bitwarden model).

**Comment by mprasil** [comment] 2020-01-29 15:07
I think this was answered? Going to close, but feel free to reopen if there are more questions regarding this.

**Closed by mprasil** 2020-01-29 15:07 UTC

**Comment by Zauberfisch** [comment] 2020-01-29 18:14
@mprasil is this issue resolved though?
As far as I can tell even what @tomuta said is just brainstorming ideas. The actual feature currently has no effect. 
Therefore I believe it would be beneficial to keep this issue open.

**Comment by Zauberfisch** [comment] 2020-01-29 18:20
yeah, just confirmed. I can delete accounts that do not have verified the email address.

**Comment by tomuta** [comment] 2020-01-29 23:24
That's the purpose of verify email. Once verified, someone else cannot delete your account, but until you do, anyone can.

**Comment by Zauberfisch** [comment] 2020-01-29 23:37
ah, right. Sorry, just woke up then and wasn't thinking straight.

But I am still not sure about your statement though. How can I delete someoneelses Account that is not verified?
Doesn't the delete thing always send a link?

**Comment by tomuta** [comment] 2020-01-30 16:11
No, if the email address hasn't been verified, deleting the account is instant and does not trigger any email to be sent. Account deletion is instant. You can test this behavior on bitwarden.com with a free account.

**Comment by tomuta** [comment] 2020-01-30 19:38
You can delete your account on the /#/recover-delete page, e.g. on bitwarden.com: https://vault.bitwarden.com/#/recover-delete

If you type in an email address that hasn't been verified, it should delete the account instantly. Otherwise, it will send an email with a link to confirm the deletion request.

**Comment by Zauberfisch** [comment] 2020-01-30 19:57
ok, I did some more testing:

- create account, delete via `#/recover-delete` (not logged in)  (NOT verified)
    > I receive a delete link via email. deleting without email is not possible
- create account, verify, delete via `#/recover-delete` (not logged in)  
    > I receive a delete link via email. deleting without email is not possible
- create account, login, delete via account settings (NOT verified)
   > Account is deleted immediately without any email
- create account, login, verify, delete via account settings
   > Account is deleted immediately without any email

so clearly, the verify email system has no effect on account deletion

**Comment by tomuta** [comment] 2020-01-30 22:02
Hm I must have remembered this wrong. You are right, it always sends an email, whether verified or not. Looking at bitwarden_rs, that's what we do as well.

**Comment by Zauberfisch** [comment] 2020-01-30 22:05
uhm. I have not tested bitwarden.com. I only tested bitwarden_rs

**Comment by sombatos** [comment] 2020-12-21 06:18
Is there any way to hide this "VERIFY EMAIL" block via CSS for example when running Bitwarden using docker?
